config/routes.rb
Rails.application.routes.draw do



  get 'tool/calculator'
  resources :events
  resources :photos
  resources :weathers
  resources :favorites
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end    
  end
  
  resources :notes

  # authenticated :user do
  #   get 'notes#index', as: "authenticated_root"
  # end
  
  get "dashboard/space"
  devise_for :users

  root "welcome#index"
  # get "/*path" , to: "welcome/index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/favorite.rb
require 'open-uri'

class Favorite < ApplicationRecord
    belongs_to :user
end

app/models/image_uploader.rb
class ImageUploader < Shrine
end    

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
    include ImageUploader[:image]
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  
  def completed?
    !completed_at.blank?
  end  
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    has_many :todo_items, :dependent => :destroy
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :notes
  has_many :todo_lists
  has_many :favorites
  has_many :events, dependent: :destroy

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def space
    @favorites = Favorite.all.where(user_id: current_user).order('created_at DESC').limit(3)
    @notes = Note.all.where(user_id: current_user).order('created_at DESC').limit(2)
    @todo_lists = TodoList.where(user_id: current_user).all.order('created_at DESC').limit(2)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def readable_time(time)
        time.strftime("%b %d, %I:%M%P")
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/tool_helper.rb
module ToolHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/space.html.erb
 <%= javascript_pack_tag 'dashboard' %>
  <%= javascript_pack_tag 'index' %>


<div id="dashboard-container">

  <div class="leftside-menu">

    <div class="avatar">
      <% if user_signed_in? %> 
         <div class="iconspace"><p><%= current_user.name.first %></p></div>
         <p class="iconp"> HELLO, <%= current_user.name.upcase %> <br> <%= current_user.email%> </p>
       <% else %>
         <div class="iconspace"><p></p></div>
         <p > Hello </p>
      <% end %>
    </div>

    <nav class="menu">
      <% if user_signed_in? %> 
      <%= link_to "EDIT PROFILE", edit_user_registration_path, class: "navsidedit" %>
      <% else%>
       <%= link_to "Sign in", new_user_session_path, class: "navside1" %>
      <% end %>    
    </nav>

  </div>

  <div class="main-grid">

    <div class="item one">
      <h1 id="spacetime" class="timespace"></h1>
      <h1 id="spacegreeting" class="timespace"></h1>
         <h2 id="spacedate" class="timespace2"></h2>

    </div>

  
    <div class="item two">
      <div class="note"> <i class="fas fa-pen"></i>  NOTES </div>
      <div class="info">
         <% @notes.each do |note|%>
     <label class="todo">
     
            <li> <div class="todo-switch1"></div>
             <%= link_to note.title, note , class: "navside" %>   
            </li>
              <% end %> 
        </label>
        <br> 
           <label>
           <%= link_to "Add Note ", new_note_path , class: "navsidenote" %> 
        </label> 
        <label>
              <%= link_to " All Notes", notes_path, class: "navsidenote"  %> 
        </label>  
      </div>
    </div>

    
    <div class="item three">
      <div class="weather">
      <br>
        <i class="fas fa-6x fa-calendar-alt"></i>
              <br><br>
        
        <%= link_to "CALENDAR", events_path, class: "navside" %>
      </div>
    </div>


    <div class="item four">
<div class="raw">
  <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
    <div class="flipper">
      <div class="front">
           <a target="_blank" href="https://pages.git.generalassemb.ly/Maram-Alfawaz/Kill-coronavirus-MaramAlfawaz/" rel="stylesheet"><i class="fas fa-gamepad"></i></a>
      </div>
    </div>
  </div>

  <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
    <div class="flipper">
      <div class="front">
         <a target="_blank" href="https://pages.git.generalassemb.ly/ghadeeralwafi/Sea-Battle-Game/#" rel="stylesheet"><i class="fas fa-ship"></i></a>
      </div>
    </div>
  </div>


  <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
    <div class="flipper">
      <div class="front">
         <a href="/tool/calculator" rel="stylesheet"><i class="fas fa-calculator"></i></a>
      </div>
      
    </div>
  </div>

  <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
    <div class="flipper">
      <div class="front">
        <a target="_blank" href="https://mercury-musics.herokuapp.com/" rel="stylesheet"><i class="fas fa-music"></i></i></a>
      </div>
    </div>
  </div>
</div>
    </div>


    <div class="item five">
      <div class="rooms--top">
        <p class="note"> <i class="fab fa-chrome"></i> DAILY WEBSITES </p>
      </div>
      <div class="rooms">
      <% @favorites.each do |favorite|%>
          <li > <div class="todo-switch1"></div>
                <%= link_to (favorite.name), "#{favorite.url}",
                  target: "_blank" , class: "navside" %>   
          </li>
        <% end %>
        <br>
           <%= link_to "Add Website", new_favorite_path , class: "navsideweb" %> 
           <%= link_to "All Websites", favorites_path , class: "navsideweb" %> 
      </div>
    </div>


 <div class="item six">
      <div class="reminders">
        <div class="reminder--btns">
        </div>
      </div>
      <div class="reminders--list">
        <label class="todo">
           <p class="note"><i class="fas fa-clipboard-check"></i> TO-DO LIST</p>
          <span class="todo-label"> 
                    <% @todo_lists.each do |todo_list|%>

            <li > <div class="todo-switch1"></div>
             <%= link_to todo_list.title, todo_list,class: "navside" %> 
          </li>
              <% end %> 
           </span>
        </label>
        <br> 
        <label>
          <%= link_to "Add List", new_todo_list_path, class: "navsidelist" %> 
        </label> 
        <label>
          <%= link_to "All Lists", todo_lists_path , class: "navsidelist" %> 
        </label>        
      </div>
    </div>
  </div>
</div>