config/routes.rb
Rails.application.routes.draw do



  get 'tool/calculator'
  resources :events
  resources :photos
  resources :weathers
  resources :favorites
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end    
  end
  
  resources :notes

  # authenticated :user do
  #   get 'notes#index', as: "authenticated_root"
  # end
  
  get "dashboard/space"
  devise_for :users

  root "welcome#index"
  # get "/*path" , to: "welcome/index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/favorite.rb
require 'open-uri'

class Favorite < ApplicationRecord
    belongs_to :user
end

app/models/image_uploader.rb
class ImageUploader < Shrine
end    

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
    include ImageUploader[:image]
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  
  def completed?
    !completed_at.blank?
  end  
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    has_many :todo_items, :dependent => :destroy
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :notes
  has_many :todo_lists
  has_many :favorites
  has_many :events, dependent: :destroy

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_note, only: [:show, :edit, :update, :destroy]

    def index
        @notes = Note.where(user_id: current_user)
    end
    
    def show
        if @note.user_id != current_user.id
            redirect_to notes_path
        end
    end
    
    def new
        @note = current_user.notes.build
    end
    
    def create
       respond_to do |format|
        @note = current_user.notes.build(note_params)
        if @note.save
            format.html { redirect_to notes_path, notice: 'Note was successfully created.' }
            format.json { render :show, status: :ok, location: @note }
        else 
            render 'new'
            format.html { render :new }
            format.json { render json: @note.errors, status: :unprocessable_entity }
        end  
    end
    end 

    
    def edit
        if @note.user_id != current_user.id
            redirect_to notes_path
        end
    end
    

    def update
        respond_to do |format|
        if @note.update(note_params)
            format.html { redirect_to notes_path, notice: 'Note was successfully updated.' }
            format.json { render :show, status: :ok, location: @note }
		else
             format.html { render :edit }
             format.json { render json: @note.errors, status: :unprocessable_entity }
        end
    end  
    end
    
    def destroy
      respond_to do |format|
        @note.destroy
        format.html { redirect_to notes_path, notice: 'Note was successfully deleted.' }
      end  
    end
    
    private

    def find_note
        @note = Note.find(params[:id])
    end
    
    def note_params
        params.require(:note).permit(:title, :content)
    end    
end

app/controllers/tool_controller.rb
class ToolController < ApplicationController
  def calculator
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def readable_time(time)
        time.strftime("%b %d, %I:%M%P")
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/tool_helper.rb
module ToolHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/notes/_form.html.erb
<div class="divBackground">
<div class="notes-form-container">
<%# <div class="wrapper-container"> %>
    <div class="wrapper">
           <div class="note_title">
       Add Note
    </div>
    <br>
		   <%= form_for(@note) do |f| %>
        <%= f.label :title %>
          <br>
            <%= f.text_field :title %><br>
              <%= f.hidden_field :content, id: :post_content %>
              <div class="trix-editor-container">
              <br>
               <%= f.label :content %>
               <br>
              <trix-editor input="post_content"></trix-editor>
              </div>
              <%= f.submit %>
           <% end %>
    </div>
<%# </div> %>
</div>
</div>

app/views/notes/edit.html.erb
<%# <div class="forms"> %>
<%= render 'form' %>
<%# </div> %>

app/views/notes/index.html.erb
<div class="divBackground1">

<div class="button-container1">
<div class="button-container2">
      <div><%= link_to 'New Note', new_note_path, class:"btn btn-danger" %></div>
</div>
</div>

<div class="main-content">
    <% @notes.each do |note| %>
      <div class="moleskine-wrapper">
      <%= link_to note do %>
        <div class="moleskine-notebook">
           <div class="notebook-cover green">
             <div class="notebook-skin">
               <p class="cover-title"><%= note.title %></p>
             </div>
           </div>
      <% end %>
      <div class="notebook-page ruled"></div>
     </div>
        <h4><%= note.title %></h4>
        </div>
     <% end %>
  
</div>

</div>

app/views/notes/new.html.erb

<%= render 'form' %>

app/views/notes/show.html.erb
<br>
<br>
<div class="button-container1">
<div class="button-container2">
      <div><%= link_to 'Edit', edit_note_path(@note) , class:"btn btn-danger mr-2" %></div>
      <div><%= link_to 'Delete', note_path(@note), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger mr-2" %></div>
</div>
</div>



<div class="note-show-container">
<div id="notebook-paper">

<div class="note-show-container">
  <div class="col-md-12 text-center">
    <div class="wrap-pencil">
      <div class="pencil-tip">
        <div class="graphite"></div>
      </div>
      <div class="pencil-body"></div>
      <div class="pencil-ereaser-keeper"></div>
      <div class="pencil-ereaser"></div>
      <div class="pencil-shadow"></div>
    </div>
  </div>
</div>

    <h1 class="note-title"><%= @note.title %></h1>

  <div id="content">
    <div class="hipsum">
       <p><%= @note.content.html_safe %></p> 
    </div>
</div>

</div>
