config/routes.rb
Rails.application.routes.draw do



  get 'tool/calculator'
  resources :events
  resources :photos
  resources :weathers
  resources :favorites
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end    
  end
  
  resources :notes

  # authenticated :user do
  #   get 'notes#index', as: "authenticated_root"
  # end
  
  get "dashboard/space"
  devise_for :users

  root "welcome#index"
  # get "/*path" , to: "welcome/index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/favorite.rb
require 'open-uri'

class Favorite < ApplicationRecord
    belongs_to :user
end

app/models/image_uploader.rb
class ImageUploader < Shrine
end    

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
    include ImageUploader[:image]
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  
  def completed?
    !completed_at.blank?
  end  
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    has_many :todo_items, :dependent => :destroy
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :notes
  has_many :todo_lists
  has_many :favorites
  has_many :events, dependent: :destroy

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.where(user_id: current_user)
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
    if @favorite.user_id != current_user.id
      redirect_to favorites_path
    end
  end

  # GET /favorites/new
  def new
    @favorite = current_user.favorites.build
  end

  # GET /favorites/1/edit
  def edit
    if @favorite.user_id != current_user.id
      redirect_to favorites_path
    end
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = current_user.favorites.build(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to favorites_path, notice: 'Favorite was successfully created.' }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to favorites_path, notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favorite_params
      params.require(:favorite).permit(:name, :url)
    end
end

app/controllers/tool_controller.rb
class ToolController < ApplicationController
  def calculator
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def readable_time(time)
        time.strftime("%b %d, %I:%M%P")
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/tool_helper.rb
module ToolHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/favorites/_form.html.erb
<div class="notes-form-container">
<%= simple_form_for(@favorite) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


  <div class="form-inputs">
  <div class="field">
    <%= f.label :name %>
    <br>
     <%= f.text_field :name %>
   </div>
  <div class="field">
    <%= f.label :url %>
    <br>
     <%= f.text_field :url %>
   </div>
  </div>

  <div class="form-actions">
  <%= f.button :submit %>
  </div> <br>
  <%= link_to 'Back', favorites_path, class: "btn submitDark" %>

<% end %>
</div>

app/views/favorites/edit.html.erb
<div class="divBackground">
<h1 class="todo_list_title">Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>


</div>

app/views/favorites/index.html.erb
<div class="divBackground">

<br>
<h1 class="h1web">Favorites WEBs</h1>
<br>
<div class="todo-list-container">
<table class="rwd-table">
  <tr>
    <th class="thweb">Name</th>
    <th class="thweb">Url</th>
    <th class="thweb" colspan="3">Setting</th>
  </tr>
      <% @favorites.each do |favorite| %>
  <tr class="trweb">
    <td class="tdweb" ><%= favorite.name %></td>
    <td class="tdweb" ><%= favorite.url %></td>
    <td class="tdweb" ><%= link_to 'Edit', edit_favorite_path(favorite) , class: "btn submitDark" %></td>
    <td class="tdweb" ><%= link_to 'Destroy', favorite,  class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
    <% end %>
      <td class="tdweb" colspan="4" style="text-align: center;">    <%= link_to 'New Favorite', new_favorite_path , class: "btn submitDark" %></td>

</table>
</div>
<br> <br>
</div>

app/views/favorites/new.html.erb
<div class="divBackground">
<h1 class="todo_list_title">New Favorite</h1><br>

<%= render 'form', favorite: @favorite %>

</div>