config/routes.rb
Rails.application.routes.draw do



  get 'tool/calculator'
  resources :events
  resources :photos
  resources :weathers
  resources :favorites
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end    
  end
  
  resources :notes

  # authenticated :user do
  #   get 'notes#index', as: "authenticated_root"
  # end
  
  get "dashboard/space"
  devise_for :users

  root "welcome#index"
  # get "/*path" , to: "welcome/index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/favorite.rb
require 'open-uri'

class Favorite < ApplicationRecord
    belongs_to :user
end

app/models/image_uploader.rb
class ImageUploader < Shrine
end    

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
    include ImageUploader[:image]
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  
  def completed?
    !completed_at.blank?
  end  
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    has_many :todo_items, :dependent => :destroy
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :notes
  has_many :todo_lists
  has_many :favorites
  has_many :events, dependent: :destroy

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.where(user_id: current_user)
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    if @todo_list.user_id != current_user.id
      redirect_to todo_lists_path
    end
  end

  # GET /todo_lists/new
  def new
    @todo_list = current_user.todo_lists.build
  end

  # GET /todo_lists/1/edit
  def edit
    if @todo_list.user_id != current_user.id
      redirect_to todo_lists_path
    end    
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.build(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
       @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/controllers/tool_controller.rb
class ToolController < ApplicationController
  def calculator
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def readable_time(time)
        time.strftime("%b %d, %I:%M%P")
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/tool_helper.rb
module ToolHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/todo_lists/_form.html.erb
<div class="todo-list-container">
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <br>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>

app/views/todo_lists/edit.html.erb
<div class="divBackground">
<h1 class="todo_list_title">Edit Todo List</h1>
<br>
<div class="forms">
	<%= render 'form', todo_list: @todo_list %>
</div>

<div class="links">
	<%= link_to 'Cancel', todo_lists_path %>
</div>
</div>

app/views/todo_lists/index.html.erb
<div class="divBackground">
<div class="todo-list-container">
<% @todo_lists.each do |todo_list| %>
<div class="index_row clearfix">
<h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
<br>
<p class="todo_list_sub_title"><%= todo_list.description %></p>
</div>
<% end %>

<div class="links">
<%= link_to "New Todo List", new_todo_list_path %>
</div>

</div>
</div>

app/views/todo_lists/new.html.erb
<div class="divBackground">
<h1 class="todo_list_title">New Todo List</h1>
<br>
<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>

<div class="links">
<%= link_to 'Back', todo_lists_path %>
</div>
</div>

app/views/todo_lists/show.html.erb
<div class="divBackground">
<div class="todo-list-container">

<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<br>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>

<div id="todo_items_wrapper">
	<%= render @todo_list.todo_items %>
	<div id="form">
		<%= render "todo_items/form" %>
	</div>
</div>



<div class="links">
	<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
	<%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" }
 %> |
  <%= link_to 'Back', todo_lists_path %>
</div>


</div>
</div>